name:                orgly
version:             0.1.0.0
github:              "schoettl/orgly"
license:             BSD3
author:              "Jakob Schöttl"
maintainer:          "jschoett@gmail.com"
copyright:           "2018 Jakob Schöttl"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/schoettl/orgly#readme>

dependencies:
- base >= 4.7 && < 5
- orgmode-parse
- attoparsec
- blaze-markup
- heterocephalus
- text
- unordered-containers
- docopt
- shelly
- regex-compat
- lens-regex
- lilypond
- MissingH

default-extensions:
- OverloadedStrings
- QuasiQuotes

library:
  source-dirs: src

executables:
  orgly:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - orgly

  orglytest:
    main:                orglytest.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - orgly

tests:
  orgly-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - orgly
